### ISSUE TITLE
session_signature isn't cleared from ajaxPrefilter when CloseSession

### ISSUE THREAD

**Issue by raelb** [imperyal/synopse-login#2] opened 2024-05-19 17:31 UTC
If you look in the server logs, you will see that `session_signature` isn't cleared after call to CloseSession. So if you login/logout multiple times, each time you will get an additional `&session_signature` appended to the request url. This actually doesn't cause any harm, since mormot only uses the last (i.e. correct) occurrence. However, probably still a good idea to clean this up.

You may use below function to do so:

```javascript
  removeSessionSignature(input) {
    // Use a regular expression to match 'session_signature=' or '&session_signature=' followed by 24 characters
    const regex = /(&?session_signature=.{24})/g;
    
    // Replace the matched pattern with an empty string
    return input.replace(regex, '');
  }
  
  // Set ajaxPrefilter function - will run on every jQuery ajax call to add the SessionSignature   */
  setAjaxPrefilter() {
      self = this;

      $.ajaxPrefilter(function(options, _, jqXHR) {    
          let new_url;
          let session_sign;
      
          if (self.getValue_FromNameAsInt('SESSION_ID') > 0 && options.url.indexOf(G_MAIN_URL) > -1) { // User is authenticated
              new_url = options.url;
              if (options.data && options.type == "GET")
              {
                  new_url      = new_url + '?' + options.data;
                  options.data = null;  // prevents jQuery from adding these to the URL
              }
              new_url = self.removeSessionSignature(new_url)
              session_sign  = self.GetSessionSignature(new_url.substr(G_SERVER_URL.length + 1));
              options.url   = new_url + session_sign;
              options.cache = true; // we don't want anti-cache "_" JQuery-parameter
          }
      });
  }
```

**Comment by imperyal** [comment] 2024-05-20 14:29
Thank you, the issue is now fixed based on your input.

**Closed as completed by imperyal** 2024-05-20 14:29 UTC
